export class MemberDefaultDetail
{
    public carCarrierId?: string;
    public  accountId?:string;
    public  groupId?:string;

    public  emdMemberEligibilityTp?:string;
    public  emdCreateFamilyInd?:string;
    public  emdCreateSpouseInd?:string;
    public  emdCreateDependentsInd?:string;
    public  emdNumberOfDependents?:string;
    public  emdNameInd?:string;
    public  emdLastName?:string;
    public  emdFirstName?:string;
    public  emdMiddleInitial?:string;
    public  emdAddressInd?:string;
    public  emdCountryInd?:string;
    public  emdCountryCode?:string;
    public  emdEmailInd?:string;
    public  emdPhoneNumberInd?:string;
    public  emdSocSecNbrInd?:string;
    public  emdSocSecNbr?:string;
    public  emdBuildSocSecNbr?:string;
    public  emdSexInd?:string;
    public  emdSex?:string;
    public  emdDurKeyInd?:string;
    public  emdDurKey?:string;
    public  emdDateOfBirthInd?:string;
    public  emdDateOfBirth?:string;
    public  emdRenewalDateInd?:string;
    public  emdRenewalDate?:string;
    public  emdEffectiveDateInd?:string;
    public  emdEffectiveDate?:string;
    public  emdThruDateInd?:string;
    public  emdThruDate?:string;
    public  emdThruDays?:string;
    public  emdMedicareHicInd?:string;
    public  emdMedicareHic?:string;
    public  emdMedicareEffDateInd?:string;
    public  emdMedicareEffDate?:string;
    public  emdMedicareCvgTypeInd?:string;
    public  emdMedicareCvgType?:string;
    public  emdPhysicianIdInd?:string;
    public  prfPrescriberId?:string;
    public  prqPrscrbrIdQualifier?:string;
    public  prfPrescriberIdState?:string;
    public  emdCareFacilityInd?:string;
    public  cfaCareFacilityId?:string;
    public  emdPersonCodeInd?:string;
    public  emdPersonCode?:string;
    public  emdFamilyTypeInd?:string;
    public  emdFamilyType?:string;
    public  emdFamilyIndicatorInd?:string;
    public  emdFamilyIndicator?:string;
    public  emdFamilyIdInd?:string;
    public  emdFamilyId?:string;
    public  emdRelationshipCodeInd?:string;
    public  emdRelationshipCode?:string;
    public  emdAlternateInsInd?:string;
    public  emdAlternateIns?:string;
    public  emdAltInsCodeInd?:string;
    public  emdAltInsCode?:string;
    public  emdAltInsuranceIdInd?:string;
    public  emdAltInsuranceId?:string;
    public  emdBrandCopayInd?:string;
    public  emdBrandCopay?:string;
    public  emdGenericCopayInd?:string;
    public  emdGenericCopay?:string;
    public  emdCopay3Ind?:string;
    public  emdCopay3?:string;
    public  emdCopay4Ind?:string;
    public  emdCopay4?:string;
    public  emdPlanInd?:string;
    public  planCode?:string;
    public  planEffDate?:string;
    public  emdLanguageCodeInd?:string;
    public  emdLanguageCode?:string;
    public  emdDurFlagInd?:string;
    public  emdDurFlag?:string;
    public  emdMultBirthCodeInd?:string;
    public  emdMultipleBirthCode?:string;
    public  emdBaseMemberIdLength?:string;
    public  emdOrigEffDateInd?:string;
    public  emdOrigEffectiveDate?:string;
    public  emdMemberTypeInd?:string;
    public  emdMemberType?:string;
    public  emdNetworkInd?:string;
    public  cnwNetworkId?:string;
    public  emdQualifierInd?:string;
    public  cquQualifierId?:string;
    public  emdCareEffDateInd?:string;
    public  emdCareEffDate?:string;
    public  emdCareThruDateInd?:string;
    public  emdCareThruDate?:string;
    public  emdClientProdCodeInd?:string;
    public  emdClientProductCode?:string;
    public  emdClientRiderCodeInd?:string;
    public  emdClientRiderCode?:string;
    public  emdMcfOvrPlanInd?:string;
    public  emdMcfOvrPlanCode?:string;
    public  emdMcfOvrPlanEffDate?:string;
    public  emdMaiEffDateInd?:string;
    public  emdMaiEffDate?:string;
    public  emdMaiThruDateInd?:string;
    public  emdMaiThruDate?:string;
    public  emdAutoTermMatchSex?:string;
    public  emdAutoTermMatchDob?:string;
    public  emdInactvFutureCovInd?:string;
    public  emdPlanEligValidation?:string;
    public  emdSsnOnErrorFile?:string;
    public  emdMaiLock?:string;
    public  emdMemberIdFormatChec?:string;
    public  emdDataFldsInd?:string;
    public  emdDataFldsEffDteInd?:string;
    public  emdDataFldsThrDteInd?:string;

    public addUserName?: string;
    public addDate?: string;
    public addTime?: string;
    public addProgramName?: string;
    public chgUserName?: string;
    public chgDate?: string;
    public chgTime?: string;
    public chgProgramName?:string;
    public message?:string;
}