export class EligRequestDetail {
    public carCarrierId?: string;
    public accountId?: string;
    public groupId?: string;  
    public erdTrackingId?: string;
    public erdLoadType?: string;
    public erdStatus?: Number;     
    public erdNbrOfMemberRecords?: string;
    public erdMemberFileName?: string;
    public erdMemberFileLibrary?: string;
    public erdNbrOfGroupRecords?: string;
    public erdGroupFileName?: string;
    public erdGroupFileLibrary?: string;
    public erdFutureDate?: string;
    public erdFileType?: string;
    public erdMediaType?: string;
    public erdCalcExplicitTrmMbr?: string;
    public erdShortInstruction?: string;
    public erdNotes?: string;
    public addUserName?: string;
    public addDate?: string;
    public addTime?: string;
    public addProgramName?: string;
    public chgUserName?: string;
    public chgDate?: string;
    public chgTime?: string;
    public chgProgramName?: string;
};