export const Constants = {
    EMPTY_STRING: "",
    REPLACE: 'R',
    DEFAULT: 'D',
    YES: 'Y',
    NO: 'N',
    ACTVIE: 'A',
    INACTIVE: 'I',
    FIELD_REQUIRED_ERR_MSG: 'This field is required.',
    VALIDATION_FAILED_ERR_MSG: 'The errors below must be corrected before saving.',
    ONE_FIELD_REQUIRED_ERR_MSG: 'One field is required.',
    JUMPLINK_GROUP_DEFAULT_DETAIL: 'GROUP_DEFAULT_DETAIL',
    DEFAULT_DETAIL_DOES_NOT_EXIST: 'Default detail doesn\'t exist.',
    SAVE_SUCCESS_MESSAGE: 'Your changes were successfully saved.',
    INVALID_DATE_MESSAGE: 'Date entered is invalid.',
    INVALID_PHONE_MESSAGE: 'Invalid phone number.',
    ONLY_ONE_FIELD_REQ: 'Only one field may be entered.',
    UNKNOWN_ERROR_OCCURED: 'An error occurred and your changes were not saved. If you continue to experience this error, please contact technical support.',
    INVALID_PLAN_CODE: 'Plan code entered is invalid',
    INVALID_THRU_DAY: 'Days entered must be between 1-999',
    DEFAULT_PLAN_CODE: '*MEMBER',
    PARAM_CARRIER_ID_KEY: 'cid',
    PARAM_ACCOUNT_ID_KEY: 'aid',
    PARAM_GROUP_ID_KEY: 'gid',
    PARAM_PLATFORM_ID_KEY: 'pid',
    PARAM_MODE_KEY: 'mode',
    DEFAULT_DATE: '01/01/0001',
    ERROR_TOLERANCE_CONTROL: 'Error Tolerance Control',
    MUST_BETWEEN_0_TO_18: 'Must be between 1-18',
    MUST_BETWEEN_0_TO_100: 'Must be between 0.01-100'
}
